Feature/memory identity (#2)
* Memory provider for identity

* Memory Identity

diff --git a/.github/workflows/publish-prod.yaml b/.github/workflows/publish-prod.yaml
--- a/.github/workflows/publish-prod.yaml
+++ b/.github/workflows/publish-prod.yaml
@@ -8,17 +8,16 @@ on:
         required: true
         type: choice
         options:
-          - identity-provider-models
-          - identity-service-models
-          - identity-provider-iota
+          - identity-models
+          - identity-connector-entity-storage
+          - identity-connector-iota
+          - identity-service
+
 jobs:
   publish:
     runs-on: ubuntu-latest
 
     if: github.ref == 'refs/heads/main'
-
-    env:
-      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
 
     steps:
       - name: Checkout
@@ -34,6 +33,16 @@ jobs:
         run: |
           rm package.json
           rm package-lock.json
+
+      - name: Check package version does not contain -next
+        run: |
+          cd packages/${{ github.event.inputs.package }}
+          PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')
+          echo Package Version $PACKAGE_VERSION
+          if [[ $PACKAGE_VERSION == *"-next"* ]]; then
+            echo "Error: package version contains -next"
+            exit 1
+          fi
 
       - name: Run Dist
         run: |
