Memory provider for identity

diff --git a/.github/workflows/publish-next.yaml b/.github/workflows/publish-next.yaml
--- a/.github/workflows/publish-next.yaml
+++ b/.github/workflows/publish-next.yaml
@@ -11,23 +11,14 @@ on:
           - identity-provider-models
           - identity-service-models
           - identity-provider-iota
-      semver:
-        description: 'What is the semver version e.g. 0.0.1'
-        default: 0.0.1
-        required: true
-      next:
-        description: 'What is the next version e.g. 1 will be appended as -next.1'
-        default: 1
-        required: true
+          - identity-provider-memory
+          - identity-service
 
 jobs:
   publish:
     runs-on: ubuntu-latest
 
     if: github.ref != 'refs/heads/main'
-
-    env:
-      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
 
     steps:
       - name: Checkout
@@ -46,17 +37,21 @@ jobs:
           rm package.json
           rm package-lock.json
 
+      - name: Check package version contains -next
+        run: |
+          cd packages/${{ github.event.inputs.package }}
+          PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')
+          echo Package Version $PACKAGE_VERSION
+          if [[ $PACKAGE_VERSION != *"-next"* ]]; then
+            echo "Error: package version does not contain -next"
+            exit 1
+          fi
+
       - name: Run Dist
         run: |
           cd packages/${{ github.event.inputs.package }}
           npm install
           npm run dist
-
-      - name: Patch package version
-        run: |
-          cd packages/${{ github.event.inputs.package }}
-          NEXT_VERSION="${{ github.event.inputs.semver }}-next.${{ github.event.inputs.next }}"
-          npm pkg set version="$NEXT_VERSION"
 
       - name: Cleanup package properties
         run: |
